name: CI

on:
  push:
    branches:
      - main

jobs:
  display-python-version-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repozytorium
      uses: actions/checkout@v2

    - name: Wyświetl wersję Pythona (Windows)
      run: python --version

  run-pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repozytorium
      uses: actions/checkout@v2

    - name: Utwórz wirtualne środowisko
      run: python -m venv venv

    - name: Aktywuj wirtualne środowisko
      run: venv\Scripts\activate

    - name: Zainstaluj zależności
      run: |
           python -m pip install --upgrade pip
           pip install pylint
      

    - name: Uruchom PyLint
      run: pylint app.py
